src/java/jpa/entities/LnsDrawings.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package jpa.entities;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;

/**
 *
 * @author Gibson Levvid
 */
@Entity
@Table(name = "LnsDrawings")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "LnsDrawings.findAll", query = "SELECT l FROM LnsDrawings l"),
    @NamedQuery(name = "LnsDrawings.findByDrawingNumber", query = "SELECT l FROM LnsDrawings l WHERE l.drawingNumber = :drawingNumber"),
    @NamedQuery(name = "LnsDrawings.findByCADFilePath", query = "SELECT l FROM LnsDrawings l WHERE l.cADFilePath = :cADFilePath")})
public class LnsDrawings implements Serializable {
    private static final long serialVersionUID = 1L;
    @Id
    @Basic(optional = false)
    @NotNull
    @Column(name = "DrawingNumber")
    private Integer drawingNumber;
    @Size(max = 255)
    @Column(name = "CADFilePath")
    private String cADFilePath;
    @JoinColumn(name = "SeriesNumber", referencedColumnName = "SeriesNumber")
    @OneToOne
    private Series seriesNumber;
    @JoinColumn(name = "DrawingSizeID", referencedColumnName = "DrawingSizeID")
    @ManyToOne
    private DrawingSize drawingSizeID;

    public LnsDrawings() {
    }

    public LnsDrawings(Integer drawingNumber) {
        this.drawingNumber = drawingNumber;
    }

    public Integer getDrawingNumber() {
        return drawingNumber;
    }

    public void setDrawingNumber(Integer drawingNumber) {
        this.drawingNumber = drawingNumber;
    }

    public String getCADFilePath() {
        return cADFilePath;
    }

    public void setCADFilePath(String cADFilePath) {
        this.cADFilePath = cADFilePath;
    }

    public Series getSeriesNumber() {
        return seriesNumber;
    }

    public void setSeriesNumber(Series seriesNumber) {
        this.seriesNumber = seriesNumber;
    }

    public DrawingSize getDrawingSizeID() {
        return drawingSizeID;
    }

    public void setDrawingSizeID(DrawingSize drawingSizeID) {
        this.drawingSizeID = drawingSizeID;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (drawingNumber != null ? drawingNumber.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof LnsDrawings)) {
            return false;
        }
        LnsDrawings other = (LnsDrawings) object;
        if ((this.drawingNumber == null && other.drawingNumber != null) || (this.drawingNumber != null && !this.drawingNumber.equals(other.drawingNumber))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "jpa.entities.LnsDrawings[ drawingNumber=" + drawingNumber + " ]";
    }
    
}

src/java/jsf/LnsDrawingsController.java
package jsf;

import java.io.IOException;
import jpa.entities.LnsDrawings;
import jsf.util.JsfUtil;
import jsf.util.PaginationHelper;
import jpa.session.LnsDrawingsFacade;

import java.io.Serializable;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;
import jpa.entities.User;

@Named("lnsDrawingsController")
@SessionScoped
public class LnsDrawingsController implements Serializable {

    private LnsDrawings current;
    private DataModel items = null;
    @EJB
    private jpa.session.LnsDrawingsFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    public LnsDrawingsController() {
    }

    public LnsDrawings getSelected() {
        if (current == null) {
            current = new LnsDrawings();
            selectedItemIndex = -1;
        }
        return current;
    }

    private LnsDrawingsFacade getFacade() {
        return ejbFacade;
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(10) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }
            };
        }
        return pagination;
    }
    
     /**Administrator privileges methods**/
    public boolean isAdmin(){
        User user = new User();
        boolean permission = false;
        try {
            permission =  user.isAdmin();
        } catch (IOException ex) {
            Logger.getLogger(LnsDrawingsController.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(LnsDrawingsController.class.getName()).log(Level.SEVERE, null, ex);
        }
        return permission;
    }
    /*End of admin privileges methods*/
    
    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (LnsDrawings) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new LnsDrawings();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/resources/Bundle").getString("LnsDrawingsCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/resources/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (LnsDrawings) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/resources/Bundle").getString("LnsDrawingsUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/resources/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (LnsDrawings) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        performDestroy();
        recreatePagination();
        recreateModel();
        return "List";
    }

    public String destroyAndView() {
        performDestroy();
        recreateModel();
        updateCurrentItem();
        if (selectedItemIndex >= 0) {
            return "View";
        } else {
            // all items were removed - go back to list
            recreateModel();
            return "List";
        }
    }

    private void performDestroy() {
        try {
            getFacade().remove(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/resources/Bundle").getString("LnsDrawingsDeleted"));
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/resources/Bundle").getString("PersistenceErrorOccured"));
        }
    }

    private void updateCurrentItem() {
        int count = getFacade().count();
        if (selectedItemIndex >= count) {
            // selected index cannot be bigger than number of items:
            selectedItemIndex = count - 1;
            // go to previous page if last page disappeared:
            if (pagination.getPageFirstItem() >= count) {
                pagination.previousPage();
            }
        }
        if (selectedItemIndex >= 0) {
            current = getFacade().findRange(new int[]{selectedItemIndex, selectedItemIndex + 1}).get(0);
        }
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    private void recreateModel() {
        items = null;
    }

    private void recreatePagination() {
        pagination = null;
    }

    public String next() {
        getPagination().nextPage();
        recreateModel();
        return "List";
    }

    public String previous() {
        getPagination().previousPage();
        recreateModel();
        return "List";
    }

    public SelectItem[] getItemsAvailableSelectMany() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), false);
    }

    public SelectItem[] getItemsAvailableSelectOne() {
        return JsfUtil.getSelectItems(ejbFacade.findAll(), true);
    }

    public LnsDrawings getLnsDrawings(java.lang.Integer id) {
        return ejbFacade.find(id);
    }

    @FacesConverter(forClass = LnsDrawings.class)
    public static class LnsDrawingsControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            LnsDrawingsController controller = (LnsDrawingsController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "lnsDrawingsController");
            return controller.getLnsDrawings(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof LnsDrawings) {
                LnsDrawings o = (LnsDrawings) object;
                return getStringKey(o.getDrawingNumber());
            } else {
                throw new IllegalArgumentException("object " + object + " is of type " + object.getClass().getName() + "; expected type: " + LnsDrawings.class.getName());
            }
        }

    }

}

web/lnsDrawings/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateLnsDrawingsTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateLnsDrawingsLabel_drawingNumber}" for="drawingNumber" />
                    <h:inputText id="drawingNumber" value="#{lnsDrawingsController.selected.drawingNumber}" title="#{bundle.CreateLnsDrawingsTitle_drawingNumber}" required="true" requiredMessage="#{bundle.CreateLnsDrawingsRequiredMessage_drawingNumber}"/>
                    <h:outputLabel value="#{bundle.CreateLnsDrawingsLabel_CADFilePath}" for="CADFilePath" />
                    <h:inputText id="CADFilePath" value="#{lnsDrawingsController.selected.CADFilePath}" title="#{bundle.CreateLnsDrawingsTitle_CADFilePath}" />
                    <h:outputLabel value="#{bundle.CreateLnsDrawingsLabel_seriesNumber}" for="seriesNumber" />
                    <h:selectOneMenu id="seriesNumber" value="#{lnsDrawingsController.selected.seriesNumber}" title="#{bundle.CreateLnsDrawingsTitle_seriesNumber}" >
                        <f:selectItems value="#{seriesController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{bundle.CreateLnsDrawingsLabel_drawingSizeID}" for="drawingSizeID" />
                    <h:selectOneMenu id="drawingSizeID" value="#{lnsDrawingsController.selected.drawingSizeID}" title="#{bundle.CreateLnsDrawingsTitle_drawingSizeID}" >
                        <f:selectItems value="#{drawingSizeController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{lnsDrawingsController.create}" value="#{bundle.CreateLnsDrawingsSaveLink}" />
                <br />
                <br />
                <h:commandLink action="#{lnsDrawingsController.prepareList}" value="#{bundle.CreateLnsDrawingsShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.CreateLnsDrawingsIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/lnsDrawings/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.EditLnsDrawingsTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditLnsDrawingsLabel_drawingNumber}" for="drawingNumber" />
                    <h:inputText id="drawingNumber" value="#{lnsDrawingsController.selected.drawingNumber}" title="#{bundle.EditLnsDrawingsTitle_drawingNumber}" required="true" requiredMessage="#{bundle.EditLnsDrawingsRequiredMessage_drawingNumber}"/>
                    <h:outputLabel value="#{bundle.EditLnsDrawingsLabel_CADFilePath}" for="CADFilePath" />
                    <h:inputText id="CADFilePath" value="#{lnsDrawingsController.selected.CADFilePath}" title="#{bundle.EditLnsDrawingsTitle_CADFilePath}" />
                    <h:outputLabel value="#{bundle.EditLnsDrawingsLabel_seriesNumber}" for="seriesNumber" />
                    <h:selectOneMenu id="seriesNumber" value="#{lnsDrawingsController.selected.seriesNumber}" title="#{bundle.EditLnsDrawingsTitle_seriesNumber}" >
                        <f:selectItems value="#{seriesController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                    <h:outputLabel value="#{bundle.EditLnsDrawingsLabel_drawingSizeID}" for="drawingSizeID" />
                    <h:selectOneMenu id="drawingSizeID" value="#{lnsDrawingsController.selected.drawingSizeID}" title="#{bundle.EditLnsDrawingsTitle_drawingSizeID}" >
                        <f:selectItems value="#{drawingSizeController.itemsAvailableSelectOne}"/>
                    </h:selectOneMenu>
                </h:panelGrid>
                <h:commandLink action="#{lnsDrawingsController.update}" value="#{bundle.EditLnsDrawingsSaveLink}"/>
                <br />
                <br />
                <h:link outcome="View" value="#{bundle.EditLnsDrawingsViewLink}"/>
                <br />
                <h:commandLink action="#{lnsDrawingsController.prepareList}" value="#{bundle.EditLnsDrawingsShowAllLink}" immediate="true"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.EditLnsDrawingsIndexLink}" />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/lnsDrawings/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
<style>
table { 
color: #333;
font-family: Helvetica, Arial, sans-serif;
width: 700px; 
border-collapse: collapse; border-spacing: 0; 
}

td, th { 
border: 1px solid transparent; /* No more visible border */
height: 30px; 
transition: all 0.3s;  /* Simple transition for hover effect */
}

th {
  /* Gradient Background */
	background: linear-gradient(#333 0%,#444 100%);
	color: #FFF; font-weight: bold;
	height: 40px;
        border-radius: 5px 5px 0 0; 
}


td {
background: #FAFAFA;
text-align: center;
width: 100%;
}

/* Cells in even rows (2,4,6...) are one color */ 
tr:nth-child(even) td { background: #F1F1F1; }   

/* Cells in odd rows (1,3,5...) are another (excludes header cells)  */ 
tr:nth-child(odd) td { background: #FEFEFE; }  

</style>
    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListLnsDrawingsTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <h:outputText escape="false" value="#{bundle.ListLnsDrawingsEmpty}" rendered="#{lnsDrawingsController.items.rowCount == 0}"/>
                <h:panelGroup rendered="#{lnsDrawingsController.items.rowCount > 0}">
                    <h:outputText value="#{lnsDrawingsController.pagination.pageFirstItem + 1}..#{lnsDrawingsController.pagination.pageLastItem + 1}/#{lnsDrawingsController.pagination.itemsCount}"/>&nbsp;
                    <h:commandLink action="#{lnsDrawingsController.previous}" value="#{bundle.Previous} #{lnsDrawingsController.pagination.pageSize}" rendered="#{lnsDrawingsController.pagination.hasPreviousPage}"/>&nbsp;
                    <h:commandLink action="#{lnsDrawingsController.next}" value="#{bundle.Next} #{lnsDrawingsController.pagination.pageSize}" rendered="#{lnsDrawingsController.pagination.hasNextPage}"/>&nbsp;
                    <h:dataTable value="#{lnsDrawingsController.items}" var="item" border="0" cellpadding="2" cellspacing="0" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListLnsDrawingsTitle_drawingNumber}"/>
                            </f:facet>
                            <h:outputText value="#{item.drawingNumber}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListLnsDrawingsTitle_CADFilePath}"/>
                            </f:facet>
                            <h:outputText value="#{item.CADFilePath}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListLnsDrawingsTitle_seriesNumber}"/>
                            </f:facet>
                            <h:outputText value="#{item.seriesNumber}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListLnsDrawingsTitle_drawingSizeID}"/>
                            </f:facet>
                            <h:outputText value="#{item.drawingSizeID}"/>
                        </h:column>
                        <h:column rendered="#{lnsDrawingsController.isAdmin() == true}">
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{lnsDrawingsController.prepareView}" value="#{bundle.ListLnsDrawingsViewLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{lnsDrawingsController.prepareEdit}" value="#{bundle.ListLnsDrawingsEditLink}"/>
                            <h:outputText value=" "/>
                            <h:commandLink action="#{lnsDrawingsController.destroy}" value="#{bundle.ListLnsDrawingsDestroyLink}"/>
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>
                <br />
                <h:commandLink action="#{lnsDrawingsController.prepareCreate}" value="#{bundle.ListLnsDrawingsCreateLink}" rendered="#{lnsDrawingsController.isAdmin() == true}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ListLnsDrawingsIndexLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/lnsDrawings/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ViewLnsDrawingsTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewLnsDrawingsLabel_drawingNumber}"/>
                    <h:outputText value="#{lnsDrawingsController.selected.drawingNumber}" title="#{bundle.ViewLnsDrawingsTitle_drawingNumber}"/>
                    <h:outputText value="#{bundle.ViewLnsDrawingsLabel_CADFilePath}"/>
                    <h:outputText value="#{lnsDrawingsController.selected.CADFilePath}" title="#{bundle.ViewLnsDrawingsTitle_CADFilePath}"/>
                    <h:outputText value="#{bundle.ViewLnsDrawingsLabel_seriesNumber}"/>
                    <h:outputText value="#{lnsDrawingsController.selected.seriesNumber}" title="#{bundle.ViewLnsDrawingsTitle_seriesNumber}"/>
                    <h:outputText value="#{bundle.ViewLnsDrawingsLabel_drawingSizeID}"/>
                    <h:outputText value="#{lnsDrawingsController.selected.drawingSizeID}" title="#{bundle.ViewLnsDrawingsTitle_drawingSizeID}"/>
                </h:panelGrid>
                <br />
                <h:commandLink action="#{lnsDrawingsController.destroyAndView}" value="#{bundle.ViewLnsDrawingsDestroyLink}"/>
                <br />
                <br />
                <h:link outcome="Edit" value="#{bundle.ViewLnsDrawingsEditLink}"/>
                <br />
                <h:commandLink action="#{lnsDrawingsController.prepareCreate}" value="#{bundle.ViewLnsDrawingsCreateLink}" />
                <br />
                <h:commandLink action="#{lnsDrawingsController.prepareList}" value="#{bundle.ViewLnsDrawingsShowAllLink}"/>
                <br />
                <br />
                <h:link outcome="/index" value="#{bundle.ViewLnsDrawingsIndexLink}"/>

            </h:form>
        </ui:define>
    </ui:composition>

</html>