src/java/jpa/entities/Author.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jpa.entities;

import java.io.Serializable;
import java.util.Collection;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlTransient;

/**
 *
 * @author Gibson Levvid
 */
@Entity
@Table(name = "Author")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Author.findAll", query = "SELECT a FROM Author a"),
    @NamedQuery(name = "Author.findByAuthorNumber", query = "SELECT a FROM Author a WHERE a.authorNumber = :authorNumber"),
    @NamedQuery(name = "Author.findByAuthorName", query = "SELECT a FROM Author a WHERE a.authorName = :authorName"),
    @NamedQuery(name = "Author.findByEmploymentStatus", query = "SELECT a FROM Author a WHERE a.employmentStatus = :employmentStatus")})
public class Author implements Serializable {

    @OneToMany(mappedBy = "originalAuthorNumber")
    private Collection<Sheet> sheetCollection;
    @OneToMany(mappedBy = "revisionAuthorNumber")
    private Collection<Sheet> sheetCollection1;
    private static final long serialVersionUID = 1L;
    @Id
    @Basic(optional = false)
    @NotNull
    @Column(name = "AuthorNumber")
    private String authorNumber;
    @Basic(optional = false)
    @NotNull
    @Size(min = 1, max = 50)
    @Column(name = "AuthorName")
    private String authorName;
    @Size(max = 50)
    @Column(name = "EmploymentStatus")
    private String employmentStatus;

    public Author() {
    }

    public Author(String authorNumber) {
        this.authorNumber = authorNumber;
    }

    public Author(String authorNumber, String authorName) {
        this.authorNumber = authorNumber;
        this.authorName = authorName;
    }

    public String getAuthorNumber() {
        return authorNumber;
    }

    public void setAuthorNumber(String authorNumber) {
        this.authorNumber = authorNumber;
    }

    public String getAuthorName() {
        return authorName;
    }

    public void setAuthorName(String authorName) {
        this.authorName = authorName;
    }

    public String getEmploymentStatus() {
        return employmentStatus;
    }

    public void setEmploymentStatus(String employmentStatus) {
        this.employmentStatus = employmentStatus;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (authorNumber != null ? authorNumber.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Author)) {
            return false;
        }
        Author other = (Author) object;
        if ((this.authorNumber == null && other.authorNumber != null) || (this.authorNumber != null && !this.authorNumber.equals(other.authorNumber))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "jpa.entities.Author[ authorNumber=" + authorNumber + " ]";
    }

    @XmlTransient
    public Collection<Sheet> getSheetCollection() {
        return sheetCollection;
    }

    public void setSheetCollection(Collection<Sheet> sheetCollection) {
        this.sheetCollection = sheetCollection;
    }

    @XmlTransient
    public Collection<Sheet> getSheetCollection1() {
        return sheetCollection1;
    }

    public void setSheetCollection1(Collection<Sheet> sheetCollection1) {
        this.sheetCollection1 = sheetCollection1;
    }

}

src/java/jsf/AuthorController.java
package jsf;

import java.io.IOException;
import java.io.Serializable;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.enterprise.context.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.model.DataModel;
import javax.faces.model.ListDataModel;
import javax.faces.model.SelectItem;
import javax.inject.Named;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.servlet.http.HttpServletRequest;
import jpa.entities.Author;
import jpa.entities.Author_;
import jpa.entities.User;
import jpa.session.AuthorFacade;
import jsf.util.JsfUtil;
import jsf.util.PaginationHelper;

@Named("authorController")
@SessionScoped
public class AuthorController implements Serializable {

    private Author current;
    private DataModel items = null;

    private int search = 0;
    private static int first = 0;
    private int last = 0;
    private int listLength = 0;
    private int itemCount = 30;
    private String searchType2 = "OR";
    private int lastPageItemCount = 0;
    private HttpServletRequest request;
    List aut;
    @EJB
    private AuthorFacade ejbFacade;
    private PaginationHelper pagination;
    private int selectedItemIndex;

    @PersistenceContext
    private EntityManager em;

    public AuthorController() {
    }

    public Author getSelected() {
        if (current == null) {
            current = new Author();
            selectedItemIndex = -1;
        }
        return current;
    }

    public int search() {
        return search;
    }

    private AuthorFacade getFacade() {
        return ejbFacade;
    }

    /**
     * Administrator privileges methods*
     */
    public boolean isAdmin() {
        User user = new User();
        boolean permission = false;
        try {
            permission = user.isAdmin();
        } catch (IOException ex) {
            Logger.getLogger(AuthorController.class.getName()).log(Level.SEVERE, null, ex);
        } catch (InterruptedException ex) {
            Logger.getLogger(AuthorController.class.getName()).log(Level.SEVERE, null, ex);
        }
        return permission;
        //return true;
    }

    /*End of admin privileges methods*/
 /*Search methods*/
    public String searchAuthors(String authorNumber, String authorName, String employmentStatus) {
        String tmp = authorName.replaceAll("[\\s\\u00A0]+$", ""); //check whether search string is empty, refresh if empty
        String tmp2 = authorNumber.replaceAll("[\\s\\u00A0]+$", ""); //check whether search string is empty, refresh if empty
        if ((tmp == "" || tmp.length() == 0) && (tmp2 == "" || tmp2.length() == 0)) {
            recreateModel();
            getItems();
            first = 0;
            search = 0;
            return "List";
        }
        search = 1;
        normalSearch(authorNumber, authorName, "AND");

        return "List";
    }

    public void normalSearch(String authorNumber, String authorName, String type) {
        String search = "SELECT a FROM Author a WHERE ";
        if (authorName.trim().length() > 0 && isString(authorName)) {
            search += analyseSearchString("authorName", authorName, type);
        }
        if (authorNumber.trim().length() > 0 && !isString(authorNumber)) {
            search += analyseSearchString("authorNumber", authorNumber, "");
        }

        if (search.trim().endsWith("OR")) {
            search = search.trim().substring(0, search.length() - 3);
        }
        if (search.trim().endsWith("AND")) {
            search = search.trim().substring(0, search.length() - 4);
        }
        if (!search.contains("AND") && authorName.trim().length() > 0 && authorNumber.trim().length() > 0) {
            search = search.substring(0, search.indexOf("a.authorNumber")) + " AND " + search.substring(search.indexOf("a.authorNumber"));
        }
        if (search.indexOf("SELECT") != 0) {
            search = search.substring(search.indexOf("SELECT", 6));
        }
        aut = em.createQuery(search).getResultList();
        //set the page data model
        listLength = aut.size();
        if (listLength > 30) {
            last = 30;
        } else {
            last = listLength();
        }

        items.setWrappedData(aut.subList(0, last));

        recreatePagination();
    }

    public String analyseSearchString(String field, String input, String type) {
        String search = "", parameter = " OR";
        if (input.contains("\"")) {
            input = input.replace("\"", "");
            parameter = " AND";
        }
        String[] longerSearch = input.trim().split(" ");
        if (longerSearch.length > 1 && ((input.trim().indexOf("\"") != 0) || (input.trim().indexOf("\"") != input.length() - 1))) {
            for (int i = 0; i < longerSearch.length; i++) {
                search += " a." + field + " LIKE " + "'%" + longerSearch[i] + "%'" + parameter;
                if (i == longerSearch.length - 1) {
                    search += " a." + field + " LIKE " + "'%" + longerSearch[i] + "%' " + type;
                } else {
                    search += " a." + field + " LIKE " + "'%" + longerSearch[i] + "%' " + parameter;
                }
            }
        } else {
            search += " a." + field + " LIKE " + "'%" + input + "%' " + type;
        }

        return search;
    }

    /*Returns true when s is a string, false when it is a number*/
    public boolean isString(String s) {
        try {
            Integer.parseInt(s);
            return false;
        } catch (NumberFormatException e) {
            return true;
        }
    }

    /**
     * Search pagination helper methods
     */
    public int first() {
        return first;
    }

    public int last() {
        return last;
    }

    public int listLength() {
        return listLength;
    }

    public boolean searchHasPrevious() {
        return first > 29;
    }

    public boolean searchHasNext() {
        return last < listLength();
    }

    public String nextSearchItems() {
        first = first + 30;
        if (last + 30 > listLength()) {
            lastPageItemCount = listLength() - last;
            last = listLength();
        } else {
            last = last + 30;
        }
        //System.out.println("NEXT: first - " + first + " :: last - " + last);
        items.setWrappedData(aut.subList(first, last));
        return "List";
    }

    public String previousSearchItems() {
        first = first - 30;
        if (lastPageItemCount != 0) {
            last = last - lastPageItemCount;
            lastPageItemCount = 0;
        } else {
            last = last - 30;
        }
        //System.out.println("PREV: first - " + first + " :: last - " + last);
        items.setWrappedData(aut.subList(first, last));
        return "List";
    }

    /**
     * *End of pagination Search helpers*
     */
    /**
     * **********************************************************************
     */
    /*End of search methods*/
 /*Browser back button*/
    public void onload() {
        if (items.getRowCount() == 0) {
            items = null;
        }
        recreatePagination();
        recreateModel();
        getPagination();
        getItems();
    }

    public DataModel getItems() {
        if (items == null) {
            items = getPagination().createPageDataModel();
        }
        return items;
    }

    /*Reset everything and show Author table*/
    public String backToAuthors() {
        recreatePagination();
        recreateModel();
        getItems();
        first = 0;
        search = 0;
        return "List";
    }

    public PaginationHelper getPagination() {
        if (pagination == null) {
            pagination = new PaginationHelper(itemCount) {

                @Override
                public int getItemsCount() {
                    return getFacade().count();
                }

                @Override
                public DataModel createPageDataModel() {
                    return new ListDataModel(getFacade().findRange(new int[]{getPageFirstItem(), getPageFirstItem() + getPageSize()}));
                }

            };
        }
        return pagination;
    }

    public String prepareList() {
        recreateModel();
        return "List";
    }

    public String prepareView() {
        current = (Author) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "View";
    }

    public String prepareCreate() {
        current = new Author();
        selectedItemIndex = -1;
        return "Create";
    }

    public String create() {
        try {
            getFacade().create(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/resources/Bundle").getString("AuthorCreated"));
            return prepareCreate();
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/resources/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String prepareEdit() {
        current = (Author) getItems().getRowData();
        selectedItemIndex = pagination.getPageFirstItem() + getItems().getRowIndex();
        return "Edit";
    }

    public String update() {
        try {
            getFacade().edit(current);
            JsfUtil.addSuccessMessage(ResourceBundle.getBundle("/resources/Bundle").getString("AuthorUpdated"));
            return "View";
        } catch (Exception e) {
            JsfUtil.addErrorMessage(e, ResourceBundle.getBundle("/resources/Bundle").getString("PersistenceErrorOccured"));
            return null;
        }
    }

    public String destroy() {
        current = (Author) getItems().getRowData();

web/author/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.CreateAuthorTitle}" styleClass="title"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:outputStylesheet library="css" name="styles.css"  />
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>

            <h:form>
                <h:commandLink action="#{authorController.prepareList}" value="#{bundle.CreateAuthorShowAllLink}" immediate="true"/>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <h:link outcome="/index" value="#{bundle.CreateAuthorIndexLink}"/>

                <br></br>
                <br></br>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.CreateAuthorLabel_authorNumber}" for="authorNumber" />
                    <h:inputText id="authorNumber" value="#{authorController.selected.authorNumber}" title="#{bundle.CreateAuthorTitle_authorNumber}" required="true" requiredMessage="#{bundle.CreateAuthorRequiredMessage_authorNumber}"/>
                    <h:outputLabel value="#{bundle.CreateAuthorLabel_authorName}" for="authorName" />
                    <h:inputText id="authorName" value="#{authorController.selected.authorName}" title="#{bundle.CreateAuthorTitle_authorName}" required="true" requiredMessage="#{bundle.CreateAuthorRequiredMessage_authorName}"/>
                    <h:outputLabel value="#{bundle.CreateAuthorLabel_employmentStatus}" for="employmentStatus" />
                    <h:inputText id="employmentStatus" value="#{authorController.selected.employmentStatus}" title="#{bundle.CreateAuthorTitle_employmentStatus}" />
                </h:panelGrid>
                <br />


                <h:commandButton styleClass = "save" action="#{authorController.create}" value="#{bundle.CreateAuthorSaveLink}"      />
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/author/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText styleClass="title" value="#{bundle.EditAuthorTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:outputStylesheet library="css" name="styles.css"  />
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>


                <h:link outcome="View" value="#{bundle.EditAuthorViewLink}"/>
                &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  
                <h:commandLink action="#{authorController.prepareList}" value="#{bundle.EditAuthorShowAllLink}" immediate="true"/>
                &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; 
                <h:link outcome="/index" value="#{bundle.EditAuthorIndexLink}" />
                &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  


                <br></br><br></br>
                <h:panelGrid columns="2">
                    <h:outputLabel value="#{bundle.EditAuthorLabel_authorNumber}" for="authorNumber" />
                    <h:inputText id="authorNumber" value="#{authorController.selected.authorNumber}" title="#{bundle.EditAuthorTitle_authorNumber}" required="true" requiredMessage="#{bundle.EditAuthorRequiredMessage_authorNumber}"/>
                    <h:outputLabel value="#{bundle.EditAuthorLabel_authorName}" for="authorName" />
                    <h:inputText id="authorName" value="#{authorController.selected.authorName}" title="#{bundle.EditAuthorTitle_authorName}" required="true" requiredMessage="#{bundle.EditAuthorRequiredMessage_authorName}"/>
                    <h:outputLabel value="#{bundle.EditAuthorLabel_employmentStatus}" for="employmentStatus" />
                    <h:inputText id="employmentStatus" value="#{authorController.selected.employmentStatus}" title="#{bundle.EditAuthorTitle_employmentStatus}" />
                </h:panelGrid>
                <br></br>

                <h:commandButton styleClass="save" action="#{authorController.update}" value="#{bundle.EditAuthorSaveLink}"/>
            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/author/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://xmlns.jcp.org/jsf/passthrough">

    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText value="#{bundle.ListAuthorTitle}"></h:outputText>

        </ui:define>
        <ui:define name="body">



            <!--Sorting helper js file-->
            <h:outputScript library="js" name="sort.js" />
            <h:outputStylesheet library="css" name="authorStyles.css"  /> 
            <h:form styleClass="jsfcrud_list_form">
                <h:panelGroup id="messagePanel" layout="block">
                    <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
                </h:panelGroup>
                <!--When no author items are found-->
                <h:panelGroup rendered="#{authorController.items.rowCount == 0}">
                    <h:outputText escape="false" value="#{bundle.ListAuthorEmpty}"/>
                    <h:commandLink action="#{authorController.backToAuthors()}" value="Author Table"/>&nbsp;
                    <h:link outcome="/index" value="#{bundle.ListAuthorIndexLink}" />&nbsp; 
                </h:panelGroup>



                <h:panelGroup class="noPrint" rendered="#{authorController.items.rowCount > 0}">


                    <h:panelGroup rendered="#{ authorController.search()==0}">
                        <h:outputText value="#{authorController.pagination.pageFirstItem + 1}..#{authorController.pagination.pageLastItem + 1}/#{authorController.pagination.itemsCount}"/>&nbsp;
                        <h:commandLink action="#{authorController.previous}" value="#{bundle.Previous} #{authorController.pagination.pageSize}" rendered="#{authorController.pagination.hasPreviousPage}"/>&nbsp;
                        <h:commandLink action="#{authorController.next}" value="#{bundle.Next} #{authorController.pagination.pageSize}" rendered="#{authorController.pagination.hasNextPage}"/>&nbsp; 
                    </h:panelGroup>

                    <!--Search next previous etc-->
                    <h:panelGroup rendered="#{ authorController.search()==1}">
                        <h:outputText value="#{authorController.first()+ 1}..#{authorController.last()}/#{authorController.listLength()}"/>&nbsp;
                        <h:commandLink action="#{authorController.previousSearchItems()}" value="#{bundle.Previous} #{authorController.pagination.pageSize}" rendered="#{authorController.searchHasPrevious()}"/>&nbsp;
                        <h:commandLink action="#{authorController.nextSearchItems()}" value="#{bundle.Next} #{authorController.pagination.pageSize}" rendered="#{authorController.searchHasNext()}"/>&nbsp; 
                    </h:panelGroup>
                    <h:commandLink action="#{authorController.prepareCreate}" value="#{bundle.ListAuthorCreateLink}" rendered="#{authorController.isAdmin() == true}"/>&nbsp; 

                    &nbsp; 
                    <h:commandLink action="#{authorController.backToAuthors()}" value="Author Table" />&nbsp; 
                    <h:link outcome="/index" value="#{bundle.ListAuthorIndexLink}" />&nbsp;


                    <br></br>
                    <!--SEARCH AUTHORS-->
                </h:panelGroup>
                <br>
                    <h:panelGroup class="noPrint">
                        <h:inputText value="#{authorNumberSearch}" size="15" p:placeholder="Author Number" styleClass="authorNumberSearch"/> &nbsp;
                        <h:inputText value="#{authorNameSearch}" size="16" p:placeholder="Author Name" styleClass="name"/>&nbsp;
                        <h:inputText value="#{authorEmploymentSearch}" size="20" p:placeholder="Employment Status" styleClass="employment"/>&nbsp;
                        <h:commandButton value="Search" action="#{authorController.searchAuthors(authorNumberSearch, authorNameSearch, authorEmploymentSearch)}"  styleClass="searchButton"/> 
                    </h:panelGroup>
                </br>


                <h:panelGroup rendered="#{authorController.items.rowCount > 0}">
                    <h:dataTable class="sortable" value="#{authorController.items}" var="item" border="0" cellpadding="3" cellspacing="3" rowClasses="jsfcrud_odd_row,jsfcrud_even_row" rules="all" style="border:solid 1px">
                        <h:column headerClass="sorttable_numeric">
                            <f:facet name="header" >
                                <h:outputText value="#{bundle.ListAuthorTitle_authorNumber}"  styleClass="column_header"/>
                            </f:facet>
                            <h:outputText value="#{item.authorNumber}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListAuthorTitle_authorName}" styleClass="column_header"/>
                            </f:facet>
                            <h:outputText value="#{item.authorName}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header">
                                <h:outputText value="#{bundle.ListAuthorTitle_employmentStatus}" styleClass="column_header"/>
                            </f:facet>
                            <h:outputText value="#{item.employmentStatus}"/>
                        </h:column>
                        <h:column rendered="#{authorController.isAdmin() == true}" headerClass="enableEdit">
                            <f:facet name="header">
                                <h:outputText value="&nbsp;"/>
                            </f:facet>
                            <h:commandLink action="#{authorController.prepareEdit}" value="#{bundle.ListAuthorEditLink}"/>&nbsp;  
                        </h:column>
                    </h:dataTable>
                </h:panelGroup>

            </h:form>
        </ui:define>
    </ui:composition>

</html>

web/author/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <ui:composition template="/template.xhtml">
        <ui:define name="title">
            <h:outputText styleClass="title" value="#{bundle.ViewAuthorTitle}"></h:outputText>
        </ui:define>
        <ui:define name="body">
            <h:outputStylesheet library="css" name="styles.css"  />
            <h:panelGroup id="messagePanel" layout="block">
                <h:messages errorStyle="color: red" infoStyle="color: green" layout="table"/>
            </h:panelGroup>
            <h:form>
                <h:commandLink action="#{authorController.prepareCreate}" value="#{bundle.ViewAuthorCreateLink}" />
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <h:commandLink action="#{authorController.prepareList}" value="#{bundle.ViewAuthorShowAllLink}"/>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <h:link outcome="/index" value="#{bundle.ViewAuthorIndexLink}"/>
                <br></br><br/>
                <h:panelGrid columns="2">
                    <h:outputText value="#{bundle.ViewAuthorLabel_authorNumber}"/>
                    <h:outputText value="#{authorController.selected.authorNumber}" title="#{bundle.ViewAuthorTitle_authorNumber}"/>
                    <h:outputText value="#{bundle.ViewAuthorLabel_authorName}"/>
                    <h:outputText value="#{authorController.selected.authorName}" title="#{bundle.ViewAuthorTitle_authorName}"/>
                    <h:outputText value="#{bundle.ViewAuthorLabel_employmentStatus}"/>
                    <h:outputText value="#{authorController.selected.employmentStatus}" title="#{bundle.ViewAuthorTitle_employmentStatus}"/>
                </h:panelGrid>
                <br />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <h:commandLink action="#{authorController.destroyAndView}" value="#{bundle.ViewAuthorDestroyLink}"/>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <h:link outcome="Edit" value="#{bundle.ViewAuthorEditLink}"/>



            </h:form>
        </ui:define>
    </ui:composition>

</html>